import bcrypt from "bcryptjs";

export const data = {
  users: [
    {
      name: "Farhad",
      email: "farhadswe35@gmail.com",
      password: bcrypt.hashSync("farhad16"),
      isAdmin: true,
    },
    {
      name: "john",
      email: "john@gmail.com",
      password: bcrypt.hashSync("john16"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Shirt",
      slug: "shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Zara",
      rating: 4.5,
      numReviews: 8,
      stock: 20,
      description: "A popular brand",
    },
    {
      name: "Normal fit Shirt",
      slug: "normal-fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "H&M",
      rating: 4.5,
      numReviews: 9,
      stock: 10,
      description: "For regular fit",
    },
    {
      name: "Slim fit Shirt",
      slug: "slim-fit-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 85,
      brand: "Tommy",
      rating: 4.5,
      numReviews: 9,
      stock: 15,
      description: "For slim fit",
    },
    {
      name: "Pant",
      slug: "pant",
      category: "Pants",
      image: "/images/pant1.jpg",
      price: 80,
      brand: "H&M",
      rating: 4.5,
      numReviews: 7,
      stock: 20,
      description: "A famous brand",
    },
    {
      name: "Regular fit Pant",
      slug: "regular-pant",
      category: "Pants",
      image: "/images/pant2.jpg",
      price: 95,
      brand: "American Eagle",
      rating: 5,
      numReviews: 9,
      stock: 5,
      description: "A famous brand for pant lover",
    },
    {
      name: "Slim fit Pant",
      slug: "slim-pant",
      category: "Pants",
      image: "/images/pant3.jpg",
      price: 60,
      brand: "Colings",
      rating: 4.5,
      numReviews: 7,
      stock: 20,
      description: "A famous brand for young",
    },
  ],
};
